In [1]:
import open3d as o3d

def read_and_show_ply(file_path):
    # Load the point cloud from the PLY file
    point_cloud = o3d.io.read_point_cloud(file_path)
    
    # Print point cloud details (e.g., number of points, xyz coordinates, and optional RGB colors)
    print("Point Cloud Information:")
    print(point_cloud)
    
    # Check if the point cloud has colors
    if point_cloud.has_colors():
        print("The point cloud has RGB values for each point.")
    
    # Check if the point cloud has normals
    if point_cloud.has_normals():
        print("The point cloud has normal vectors for each point.")
    
    # Visualize the point cloud
    o3d.visualization.draw_geometries([point_cloud])

# Example usage:
file_path = '/home/csslab/Documents/Aqsa/jupyter/points3D_colmap.ply'  # Replace with the actual file path
read_and_show_ply(file_path)


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Point Cloud Information:
PointCloud with 1688 points.
The point cloud has RGB values for each point.
The point cloud has normal vectors for each point.


In [13]:
import open3d as o3d

def read_and_show_ply(file_path):
    # Load the point cloud from the PLY file
    point_cloud = o3d.io.read_point_cloud(file_path)
    
    # Print point cloud details (e.g., number of points, xyz coordinates, and optional RGB colors)
    print("Point Cloud Information:")
    print(point_cloud)
    
    # Check if the point cloud has colors
    if point_cloud.has_colors():
        print("The point cloud has RGB values for each point.")
    
    # Check if the point cloud has normals
    if point_cloud.has_normals():
        print("The point cloud has normal vectors for each point.")
    
    # Visualize the point cloud
    o3d.visualization.draw_geometries([point_cloud])

# Example usage:
file_path = '/home/csslab/Documents/Aqsa/jupyter/points_mast3r.ply'  # Replace with the actual file path
read_and_show_ply(file_path)
file_path = '/home/csslab/Documents/Aqsa/jupyter/points_reduction.ply'  # Replace with the actual file path
read_and_show_ply(file_path)


Point Cloud Information:
PointCloud with 516684 points.
The point cloud has RGB values for each point.
The point cloud has normal vectors for each point.
Point Cloud Information:
PointCloud with 580034 points.
The point cloud has RGB values for each point.
The point cloud has normal vectors for each point.


In [10]:
import open3d as o3d
import numpy as np

# Load the PLY file
ply_file = "/home/csslab/Documents/Aqsa/jupyter/points_mast3r.ply"
point_cloud = o3d.io.read_point_cloud(ply_file)

# Get the color data (red, green, blue)
colors = np.asarray(point_cloud.colors)  # Colors will be in range [0, 1]

# Convert color values to range [0, 255] if necessary
colors = (colors * 255).astype(int)

# Count how many points are black (R=0, G=0, B=0)
black_points_count = np.sum(np.all(colors == [0, 0, 0], axis=1))

print(f"Number of black points: {black_points_count}")


Number of black points: 33


In [14]:
from pyntcloud import PyntCloud

def read_ply_unknown_pyntcloud(file_path):
    """
    Read a .ply file using PyntCloud and dynamically extract all available properties.
    
    :param file_path: Path to the .ply file.
    :return: Pandas DataFrame containing the available properties.
    """
    # Load the PLY file using PyntCloud
    cloud = PyntCloud.from_file(file_path)

    # Convert to a pandas DataFrame for easy access
    data_frame = cloud.points

    # Print available columns (properties) in the PLY file
    print("Properties found in the PLY file:", data_frame.columns)

    # Print a sample of the data to see the structure
    print("Sample data from PLY file:\n", data_frame.head())

    return data_frame


# Example usage
ply_file_path = '/home/csslab/Documents/Aqsa/jupyter/points_reduction.ply'
data = read_ply_unknown_pyntcloud(ply_file_path)

# Example: If you want to access 'x', 'y', 'z' and 'rgb' if they exist
if 'x' in data and 'y' in data and 'z' in data:
    xyz = data[['x', 'y', 'z']].to_numpy()
    print("XYZ coordinates:\n", xyz[:5])

if 'red' in data and 'green' in data and 'blue' in data:
    rgb = data[['red', 'green', 'blue']].to_numpy()
    print("RGB values:\n", rgb[:5])

if 'nx' in data and 'ny' in data and 'nz' in data:
    normals = data[['nx', 'ny', 'nz']].to_numpy()
    print("Normals:\n", normals[:5])


Properties found in the PLY file: Index(['x', 'y', 'z', 'nx', 'ny', 'nz', 'red', 'green', 'blue'], dtype='object')
Sample data from PLY file:
           x         y         z        nx        ny        nz  red  green  \
0 -3.734488 -3.802806  2.099216 -0.226131  0.957520  0.178944   51     86   
1 -3.742579 -3.793993  2.083892  0.245815 -0.962023 -0.118685   71    104   
2 -3.775132 -3.818878  2.087590 -0.273783  0.946019  0.173467   77    110   
3 -3.790827 -3.820519  2.078157 -0.284002  0.948191  0.142396   70    101   
4 -3.697240 -3.791003  2.084136 -0.055084  0.940149  0.336283   62    100   

   blue  
0    35  
1    56  
2    65  
3    58  
4    48  
XYZ coordinates:
 [[-3.734488  -3.8028064  2.0992165]
 [-3.7425785 -3.793993   2.0838923]
 [-3.7751317 -3.8188777  2.0875897]
 [-3.7908273 -3.8205194  2.078157 ]
 [-3.6972404 -3.7910032  2.0841355]]
RGB values:
 [[ 51  86  35]
 [ 71 104  56]
 [ 77 110  65]
 [ 70 101  58]
 [ 62 100  48]]
Normals:
 [[-0.22613107  0.95751965  0.1789438

In [11]:
from pyntcloud import PyntCloud

def read_ply_unknown_pyntcloud(file_path):
    """
    Read a .ply file using PyntCloud and dynamically extract all available properties.
    
    :param file_path: Path to the .ply file.
    :return: Pandas DataFrame containing the available properties.
    """
    # Load the PLY file using PyntCloud
    cloud = PyntCloud.from_file(file_path)

    # Convert to a pandas DataFrame for easy access
    data_frame = cloud.points

    # Print available columns (properties) in the PLY file
    print("Properties found in the PLY file:", data_frame.columns)

    # Print a sample of the data to see the structure
    print("Sample data from PLY file:\n", data_frame.head())

    return data_frame


# Example usage
ply_file_path = '/home/csslab/Documents/Aqsa/jupyter/points_mast3r.ply'
data = read_ply_unknown_pyntcloud(ply_file_path)
# Count how many points are black (R=0, G=0, B=0)
black_points_count = len(data[(data['red'] == 0) & (data['green'] == 0) & (data['blue'] == 0)])

print(f"Number of black points: {black_points_count}")

# Example: If you want to access 'x', 'y', 'z' and 'rgb' if they exist
if 'x' in data and 'y' in data and 'z' in data:
    xyz = data[['x', 'y', 'z']].to_numpy()
    print("XYZ coordinates:\n", xyz[:5])

if 'red' in data and 'green' in data and 'blue' in data:
    rgb = data[['red', 'green', 'blue']].to_numpy()
    print("RGB values:\n", rgb[:5])

if 'nx' in data and 'ny' in data and 'nz' in data:
    normals = data[['nx', 'ny', 'nz']].to_numpy()
    print("Normals:\n", normals[:5])



Properties found in the PLY file: Index(['x', 'y', 'z', 'nx', 'ny', 'nz', 'red', 'green', 'blue'], dtype='object')
Sample data from PLY file:
           x         y         z        nx        ny        nz  red  green  \
0 -3.730344 -3.797073  2.095966  0.074878  0.474121  0.877270   51     86   
1 -3.745526 -3.798059  2.086190 -0.063077  0.405346  0.911985   71    104   
2 -3.760260 -3.798439  2.076077  0.616490 -0.257214 -0.744165   77    110   
3 -3.773743 -3.797121  2.065019  0.787790 -0.401400 -0.467188   70    101   
4 -3.708975 -3.807354  2.093380  0.228064  0.164812  0.959596   62    100   

   blue  
0    35  
1    56  
2    65  
3    58  
4    48  
Number of black points: 33
XYZ coordinates:
 [[-3.7303443 -3.797073   2.0959659]
 [-3.7455258 -3.7980585  2.0861897]
 [-3.76026   -3.798439   2.0760775]
 [-3.7737427 -3.797121   2.0650191]
 [-3.7089753 -3.8073545  2.09338  ]]
RGB values:
 [[ 51  86  35]
 [ 71 104  56]
 [ 77 110  65]
 [ 70 101  58]
 [ 62 100  48]]
Normals:
 [[ 0.0748

In [2]:
from pyntcloud import PyntCloud

def read_ply_unknown_pyntcloud(file_path):
    """
    Read a .ply file using PyntCloud and dynamically extract all available properties.
    
    :param file_path: Path to the .ply file.
    :return: Pandas DataFrame containing the available properties.
    """
    # Load the PLY file using PyntCloud
    cloud = PyntCloud.from_file(file_path)

    # Convert to a pandas DataFrame for easy access
    data_frame = cloud.points

    # Print available columns (properties) in the PLY file
    print("Properties found in the PLY file:", data_frame.columns)

    # Print a sample of the data to see the structure
    print("Sample data from PLY file:\n", data_frame.head())

    return data_frame


# Example usage
ply_file_path = '/home/csslab/Documents/Aqsa/GS/test_gaussian/tandt/tandt/truck/sparse/0/points3D.ply'
data = read_ply_unknown_pyntcloud(ply_file_path)

# Example: If you want to access 'x', 'y', 'z' and 'rgb' if they exist
if 'x' in data and 'y' in data and 'z' in data:
    xyz = data[['x', 'y', 'z']].to_numpy()
    print("XYZ coordinates:\n", xyz[:5])

if 'red' in data and 'green' in data and 'blue' in data:
    rgb = data[['red', 'green', 'blue']].to_numpy()
    print("RGB values:\n", rgb[:5])

if 'nx' in data and 'ny' in data and 'nz' in data:
    normals = data[['nx', 'ny', 'nz']].to_numpy()
    print("Normals:\n", normals[:5])


Properties found in the PLY file: Index(['x', 'y', 'z', 'nx', 'ny', 'nz', 'red', 'green', 'blue'], dtype='object')
Sample data from PLY file:
           x         y         z   nx   ny   nz  red  green  blue
0 -0.128164  1.443515 -0.604436  0.0  0.0  0.0  126    123   144
1 -1.049939 -0.063026 -0.565611  0.0  0.0  0.0  206    218   233
2 -0.268487 -0.321693  1.285138  0.0  0.0  0.0   98     96   111
3 -0.487946 -0.309079 -0.137188  0.0  0.0  0.0   80     59    56
4 -1.033650 -0.086654 -0.536572  0.0  0.0  0.0  237    255   255
XYZ coordinates:
 [[-0.12816392  1.4435146  -0.60443616]
 [-1.049939   -0.06302593 -0.5656106 ]
 [-0.26848674 -0.3216928   1.2851381 ]
 [-0.4879458  -0.30907938 -0.13718756]
 [-1.0336503  -0.08665371 -0.536572  ]]
RGB values:
 [[126 123 144]
 [206 218 233]
 [ 98  96 111]
 [ 80  59  56]
 [237 255 255]]
Normals:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
from pyntcloud import PyntCloud

def read_ply_unknown_pyntcloud(file_path):
    """
    Read a .ply file using PyntCloud and dynamically extract all available properties.
    
    :param file_path: Path to the .ply file.
    :return: Pandas DataFrame containing the available properties.
    """
    # Load the PLY file using PyntCloud
    cloud = PyntCloud.from_file(file_path)

    # Convert to a pandas DataFrame for easy access
    data_frame = cloud.points

    # Print available columns (properties) in the PLY file
    print("Properties found in the PLY file:", data_frame.columns)

    # Print a sample of the data to see the structure
    print("Sample data from PLY file:\n", data_frame.head())

    return data_frame


# Example usage
ply_file_path = '/home/csslab/Documents/Aqsa/jupyter/output_point_cloud_mast3r.ply'
data = read_ply_unknown_pyntcloud(ply_file_path)

# Example: If you want to access 'x', 'y', 'z' and 'rgb' if they exist
if 'x' in data and 'y' in data and 'z' in data:
    xyz = data[['x', 'y', 'z']].to_numpy()
    print("XYZ coordinates:\n", xyz[:5])

if 'red' in data and 'green' in data and 'blue' in data:
    rgb = data[['red', 'green', 'blue']].to_numpy()
    print("RGB values:\n", rgb[:5])

if 'nx' in data and 'ny' in data and 'nz' in data:
    normals = data[['nx', 'ny', 'nz']].to_numpy()
    print("Normals:\n", normals[:5])


Properties found in the PLY file: Index(['x', 'y', 'z', 'nx', 'ny', 'nz', 'f_dc_0', 'f_dc_1', 'f_dc_2',
       'f_rest_0', 'f_rest_1', 'f_rest_2', 'f_rest_3', 'f_rest_4', 'f_rest_5',
       'f_rest_6', 'f_rest_7', 'f_rest_8', 'f_rest_9', 'f_rest_10',
       'f_rest_11', 'f_rest_12', 'f_rest_13', 'f_rest_14', 'f_rest_15',
       'f_rest_16', 'f_rest_17', 'f_rest_18', 'f_rest_19', 'f_rest_20',
       'f_rest_21', 'f_rest_22', 'f_rest_23', 'f_rest_24', 'f_rest_25',
       'f_rest_26', 'f_rest_27', 'f_rest_28', 'f_rest_29', 'f_rest_30',
       'f_rest_31', 'f_rest_32', 'f_rest_33', 'f_rest_34', 'f_rest_35',
       'f_rest_36', 'f_rest_37', 'f_rest_38', 'f_rest_39', 'f_rest_40',
       'f_rest_41', 'f_rest_42', 'f_rest_43', 'f_rest_44', 'opacity',
       'scale_0', 'scale_1', 'scale_2', 'rot_0', 'rot_1', 'rot_2', 'rot_3'],
      dtype='object')
Sample data from PLY file:
           x         y         z   nx   ny   nz    f_dc_0    f_dc_1    f_dc_2  \
0 -3.713475 -3.781651  2.055275  0.0  0.

In [12]:
import open3d as o3d

def read_and_show_ply(file_path):
    # Load the point cloud from the PLY file
    point_cloud = o3d.io.read_point_cloud(file_path)
    
    # Print point cloud details (e.g., number of points, xyz coordinates, and optional RGB colors)
    print("Point Cloud Information:")
    print(point_cloud)
    
    # Check if the point cloud has colors
    if point_cloud.has_colors():
        print("The point cloud has RGB values for each point.")
    
    # Check if the point cloud has normals
    if point_cloud.has_normals():
        print("The point cloud has normal vectors for each point.")
    
    # Visualize the point cloud
    o3d.visualization.draw_geometries([point_cloud])

# Example usage:
file_path = '/home/csslab/Documents/Aqsa/jupyter/output_point_cloud_colmap.ply'  # Replace with the actual file path
read_and_show_ply(file_path)
file_path = '/home/csslab/Documents/Aqsa/jupyter/output_point_cloud_mast3r.ply'  # Replace with the actual file path
read_and_show_ply(file_path)
file_path = '/home/csslab/Documents/Aqsa/jupyter/point_cloud_100.ply'  # Replace with the actual file path
read_and_show_ply(file_path)



Point Cloud Information:
PointCloud with 990896 points.
The point cloud has normal vectors for each point.
Point Cloud Information:
PointCloud with 3021817 points.
The point cloud has normal vectors for each point.
Point Cloud Information:
PointCloud with 3218791 points.
The point cloud has normal vectors for each point.
Point Cloud Information:
PointCloud with 580034 points.
The point cloud has RGB values for each point.
The point cloud has normal vectors for each point.
